# Generated by Django 4.2.11 on 2024-05-05 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RemoveField(
            model_name='list',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='listapp.list')),
            ],
            options={
                'ordering': ['-complete'],
            },
        ),
    ]
