# Generated by Django 4.2.11 on 2024-05-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_alter_list_options_remove_list_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='list',
            name='slug',
        ),
    ]
